# Site settings
title: Hi! I'm Matt
email: your-email@domain.com
url: https://example.github.io
description: "I'm a junior economics and math double major at Carleton College in Northfield, MN. I am interested in economics, economic research, public policy, data, statistics, and analytics."
# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Your Website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: LinkedIn
    url: http://linkedin.com/kayem20
  - title: github
    url: https://github.com/mrkaye97

# Build settings
markdown: kramdown
permalink: pretty
