# Site settings
title:
email: kayem@carleton.edu
url: https://mrkaye97.github.io
description: "Hi! I'm Matt, a junior economics and math double major at Carleton College in Northfield, MN. I am interested in economics, economic research, public policy, data, statistics, and analytics."
permalink: /:categories/:year/:month/:day/:title:output_ext

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Your Website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/kayem20/
  - title: github
    url: https://github.com/mrkaye97

# Build settings
markdown: kramdown
permalink: pretty
