# Site settings
title: Home
email: kayem@carleton.edu
url: https://mrkaye97.github.io
description: "Hi!"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: home

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: http://linkedin.com/kayem20
  - title: github
    url: https://github.com/mrkaye97

# Build settings
markdown: kramdown
permalink: pretty
