# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://mrkaye97.github.io
title: Home
email: kayem@carleton.edu
author: Matthew Kaye
description: > # "Hi! I'm Matt, a junior economics and mathematics double major at Carleton College in Northfield, Minnesota. I'm interested in economic research, public policy, statistics, data analytics, and data visualization. This is my home page! Check out my LinkedIn, GitHub, and blog!
copyright: 'Copyright &copy; 2018 Matthew Kaye All Rights Reserved.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    url: https://github.com/mrkaye97
  - title: linkedin
    url: https://www.linkedin.com/in/kayem20/
