project:
  type: website
  output-dir: docs
  preview:
    port: 4321
    browser: true

description-meta: "Matt Kaye's personal website."

website:
  title: "Matt Kaye"
  site-url: "https://www.matthewrkaye.com"
  repo-url: https://github.com/mrkaye97/mrkaye97.github.io
  description: "Matt Kaye's personal website"
  google-analytics: "G-J4CH9BY1RY"
  cookie-consent: true
  search:
    location: navbar
    type: textbox
  navbar:
    left:
      - text: "Blog"
        menu:
          - text: "Posts"
            file: posts.qmd
          - text: "Series"
            file: series.qmd
      - text: "Code"
        file: code.qmd
      - text: Resume
        file: "/resume/Matthew_Kaye_Resume.pdf"
      - text: "More"
        menu:
          - text: "My three favorite"
            file: my-three-favorite.qmd
          - text: "Statistics in the wild"
            file: stats-in-the-wild.qmd
          - text: "Going places"
            file: travel.qmd
          - text: "Blogroll"
            file: blogroll.qmd
    right:
      - icon: rss
        href: posts.xml

  page-footer:
    left: |
      {{< fa regular copyright >}} Matt Kaye, 2023<br>

    right: |
      Built in R with [Quarto](https://quarto.org/) and ❤<br>
      [Source at {{< fa brands github >}} GitHub](https://github.com/mrkaye97/mrkaye97.github.io)

format:
  html:
    theme:
      light: [cosmo, theme-light.scss]
    css: styles.css
    toc: true

editor:
  mode: source
