---
toc: false
---

I like writing code for fun, to explore interesting questions and problems, and to improve the tools I use. 

Broadly speaking, I'd break down this work into four buckets: [ZenSearch](https://zensearch.jobs), R packages I author or maintain, contributions to open-source libraries, and other side projects.

ZenSearch
-------------------------------------
[ZenSearch](https://zensearch.jobs) is a NextJS / FastAPI app I've been building to make your job hunt more sane. [You can read about it on my blog](https://matthewrkaye.com/posts/2023-11-10-jobcrawler/jobcrawler.html). 

R Packages
-------------------------------------

* **[slackr](https://matthewrkaye.com/slackr/)** is an R wrapper of the Slack API
* **[fitbitr](https://matthewrkaye.com/fitbitr/)** is an R wrapper of the Fitbit API
* **[lightMLFlow](https://github.com/collegevine/lightMLFlow)** is an opinionated R wrapper of the MLFlow REST API

Open-Source Contributions
-------------------------------------
* [Adding JSON schema validation to MLFlow](https://github.com/mlflow/mlflow/pull/5458)
* [Adding a MAP@K implementation to `recmetrics`](https://github.com/statisticianinstilettos/recmetrics/pull/50)
* [Adding a minimal CI/CD process to `recmetrics`](https://github.com/statisticianinstilettos/recmetrics/pull/52)

Miscellaneous Side Projects
-------------------------------------
* A writeup of my team's submission to the 2021 NFL Big Data Bowl lives on our [Github Pages site](https://hjmbigdatabowl.github.io/bdb2021/articles/submission.html).
* An over-the-top (yet imperfect) R solution to one of our data science technical interview questions: (roughly) implement K-Means lives in my [ugly-kmeans repo](https://github.com/mrkaye97/ugly-kmeans).
* The code behind a cursory exploration of the tail behavior of ESPN's college football win probably model lives in my [espn-cfb-win-prob repo](https://github.com/mrkaye97/espn-cfb-win-prob).
