---
title: My Three Favorite, Alphabetically
toc: false
---

*   **ALGORITHMS:** [Bogo Sort](https://en.wikipedia.org/wiki/Bogosort), [Logistic Regression](https://en.wikipedia.org/wiki/Logistic_regression), [Metropolis-Hastings](https://en.wikipedia.org/wiki/Metropolis%E2%80%93Hastings_algorithm)
*   **ARTISTS (Musical, According to Spotify):** Bad Bunny, Imagine Dragons, Taylor Swift
*   **AUTHORS:** Fredrik Backman, Khaled Hosseini, Sally Rooney
*   **BEERS:** [Heady Topper](https://untappd.com/b/the-alchemist-heady-topper/4691) -- _The Alchemist_ , [King Sue](https://untappd.com/b/toppling-goliath-brewing-co-king-sue/594015) -- _Toppling Goliath_, [Very Green](https://untappd.com/b/tree-house-brewing-company-very-green/689944) -- _Tree House_
*   **BOOKS (Fiction):** [_The Kite Runner_](https://app.thestorygraph.com/books/6c6726eb-8580-4be7-ab60-5ccd073d7ae5), [_Neverwhere_](https://app.thestorygraph.com/books/148a1a01-1f5f-440e-8239-f641afa637e0), [_A Storm of Swords_](https://app.thestorygraph.com/books/ff263f0f-121e-41d2-b2ba-b261fc974cc3)
*   **BOOKS (Non-Fiction):** [_Algorithms to Live By_](https://app.thestorygraph.com/books/b5d084fb-6417-4803-8a47-da827d3d7270), [_The Signal and the Noise_](https://app.thestorygraph.com/books/b771dbda-1528-4886-8814-b530b3a07431), [_Factfulness_](https://app.thestorygraph.com/books/dedebd43-d2f7-4f9e-8ee3-b73671df1311)
*   **CITIES (American):** Boston, New York City, San Diego
*   **CITIES (European):** Barcelona, Budapest, Stockholm
*   **CITIES (Other):** Medellín, Oaxaca, Vancouver
*   **COLLEGE COURSES:** Advanced Algorithms, Mathematical Structures, Price Theory
*   **CONDIMENTS:** Calabrian Chiles, Preserved Lemons, Secret Aardvark Hot Sauce
*   **CUISINES (Couldn't pick three):** Italian, Japanese, Lebanese, Mexican
*   **DATA STRUCTURES:** [Graph](https://en.wikipedia.org/wiki/Graph_(abstract_data_type)), [Skip List](https://en.wikipedia.org/wiki/Skip_list), [Tibble](https://tibble.tidyverse.org/)
*   **ECONOMIC SUBFIELDS:** Labor Economics, Monetary Theory, Urban Economics
*   **FICTIONAL CHARACTERS:** Elaine Benes, Oberyn Martell, Samwise Gamgee
*   **FOODS:** Bananas, Maitake Mushrooms, Peanut Butter
*   **KITCHEN UTENSILS:** 7" Santoku Knife, Tasting Spoon, Tongs
*   **MOVIES:** [Birdman](https://www.rottentomatoes.com/m/birdman_2014), [Inside Out](https://www.rottentomatoes.com/m/inside_out_2015), [Moonrise Kingdom](https://www.rottentomatoes.com/m/moonrise_kingdom)
*   **NON-CITY PLACES:** Acadia National Park, Baseball Hall of Fame, Little Cottonwood Canyon
*   **PARADIGMS:** [Bayesian](https://en.wikipedia.org/wiki/Bayesian_statistics), [Behavioral](https://en.wikipedia.org/wiki/Behavioral_economics), [Functional](https://en.wikipedia.org/wiki/Functional_programming)
*   **PIECES OF COOKWARE:** 3-Quart Saute Pan, Cast Iron Skillet, Dutch Oven
*   **R PACKAGES:** [brms](https://paul-buerkner.github.io/brms/), [dplyr](https://dplyr.tidyverse.org/), [purrr](https://purrr.tidyverse.org/)
*   **SERIOUSEATS RECIPES:** [Halal Cart Chicken](https://www.seriouseats.com/recipes/2011/12/serious-eats-halal-cart-style-chicken-and-rice-white-sauce-recipe.html), [Pozole Verde with Chicken](https://www.seriouseats.com/recipes/2017/01/pozole-verde-de-pollo-green-mexican-hominy-and-chicken-soup-recipe.html), [Red Wine-Braised Short Ribs](https://www.seriouseats.com/recipes/2019/12/red-wine-braised-beef-short-ribs-recipe.html)
*   **SKI MOUNTAINS:** Alta, Big Sky, Jackson Hole
*   **SPIRITS:** Fernet, Islay Scotch, Mezcal
*   **SPORTS TO WATCH:** Baseball, College Football, Soccer
*   **SUBREDDITS:** [AdvancedRunning](https://www.reddit.com/r/AdvancedRunning), [MaleLivingSpace](https://www.reddit.com/r/MaleLivingSpace), [UnexpectedFactorial](https://www.reddit.com/r/UnexpectedFactorial)
*   **TV SHOWS:** [Atlanta](https://www.rottentomatoes.com/tv/atlanta), [Chef's Table](https://www.rottentomatoes.com/tv/chef_s_table), [Seinfeld](https://www.rottentomatoes.com/tv/seinfeld)
*   **WEBSITES:** [Fangraphs](https://www.fangraphs.com/), [FiveThirtyEight](https://fivethirtyeight.com/), [Serious Eats](http://www.seriouseats.com/)
